# Accessing and filtering data
You are working on a Python application to display information about the dogs available for adoption at your local animal shelter. Some of the variables of interest, such as "breed", `"size"`, and `"coat"`, are saved as categorical variables. In order for this application to work properly, you need to be able to access and filter data using these columns.

The `ID` variable has been set as the index of the `pandas` DataFrame `dogs`.

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
file='ShelterDogs.csv'
path=r"D:\\Cursos\\Data_Science_Python\\data_sets\\"
pathfile=path+file
try:
 df= pd.read_csv(pathfile)
 print(df.head(5))
except :
  print('file doesnt exist')

dogs = df[:]

      ID            name   age     sex               breed date_found  \
0  23807            Gida  0.25  female         Unknown Mix   12/10/19
1    533  Frida És Ricsi  0.17  female         Unknown Mix    12/1/19
2  23793             NaN  4.00    male         Unknown Mix    12/8/19
3  23795             NaN  1.00    male         Unknown Mix    12/8/19
4  23806             Amy  2.00  female  French Bulldog Mix   12/10/19

  adoptable_from    posted            color    coat    size neutered  \
0       12/11/19  12/11/19              red   short   small       no
1        12/1/19   12/9/19  black and white   short   small       no
2       12/23/19   12/8/19      saddle back   short  medium       no
3       12/23/19   12/8/19     yellow-brown  medium  medium       no
4       12/11/19  12/11/19            black   short   small       no

  housebroken likes_people likes_children get_along_males get_along_females  \
0         NaN          NaN            NaN             NaN               NaN
1         NaN          yes            yes             yes               yes
2         NaN          NaN            NaN             NaN               NaN
3         NaN          NaN            NaN             NaN               NaN
4         NaN          NaN            NaN             NaN               NaN

  get_along_cats keep_in
0            NaN     NaN
1            yes     NaN
2            NaN     NaN
3            NaN     NaN
4            NaN     NaN

* Print the `"coat"` value for the dog with an `ID` of 23807.

In [2]:
# Print the category of the coat for ID 23807
print(dogs.loc[dogs['ID']==23807, "coat"])

0    short
Name: coat, dtype: object

In [3]:
dogs.set_index('ID')

,name,age,sex,breed,date_found,adoptable_from,posted,color,coat,size,neutered,housebroken,likes_people,likes_children,get_along_males,get_along_females,get_along_cats,keep_in
ID,,,,,,,,,,,,,,,,,,
23807,Gida,0.25,female,Unknown Mix,12/10/19,12/11/19,12/11/19,red,short,small,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN
533,Frida És Ricsi,0.17,female,Unknown Mix,12/1/19,12/1/19,12/9/19,black and white,short,small,no,NaN,yes,yes,yes,yes,yes,NaN
23793,NaN,4.00,male,Unknown Mix,12/8/19,12/23/19,12/8/19,saddle back,short,medium,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23795,NaN,1.00,male,Unknown Mix,12/8/19,12/23/19,12/8/19,yellow-brown,medium,medium,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23806,Amy,2.00,female,French Bulldog Mix,12/10/19,12/11/19,12/11/19,black,short,small,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118,Fodri,16.92,male,Unknown Mix,12/25/03,12/25/03,3/22/06,yellow-brown,short,medium,no,no,yes,yes,no,yes,no,garden
262,Csibi,17.33,female,Staffordshire Terrier Mix,8/27/04,8/27/04,7/8/05,striped,short,large,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Konrád,18.17,male,Unknown Mix,9/21/05,9/21/05,10/26/05,black,short,medium,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN
141,Kölni,17.17,male,Unknown Mix,11/27/04,11/27/04,5/2/05,black and brown,medium,medium,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN
248,Kedves,16.08,male,"German Shepherd Dog, Hound Mix",4/2/05,4/2/05,6/30/05,sable,short,medium,yes,NaN,yes,NaN,yes,yes,NaN,both flat and garden

In [7]:
# Print the category of the coat for ID 23807
print(dogs.loc[dogs['ID']==23807, "coat"])

0    short
Name: coat, dtype: object


For dogs with a long "coat", print the number of each "sex"

In [8]:
# Find the count of male and female dogs who have a "long" coat
print(dogs.loc[dogs['coat']=="long", 'sex'].value_counts())

male      124
female     56
Name: sex, dtype: int64

* Print the average age of dogs with a `"breed"` of "English Cocker Spaniel".

In [9]:
# Print the mean age of dogs with a breed of "English Cocker Spaniel"
print(dogs.loc[dogs['breed']=="English Cocker Spaniel", 'age'].mean())

8.186153846153847

Filter to the dogs with "English" in their `"breed"` name using the .contains() method.

In [10]:
# Count the number of dogs that have "English" in their breed name
print(dogs[dogs["breed"].str.contains('English', regex=False)].shape[0])

35